### ISSUE TITLE
does not start on latest python

### ISSUE THREAD

**Issue by salos1982** [philtabor/Youtube-Code-Repository#5]
Hello, I'm trying to start your example lunar_lander.py but it is not started. I have follwoing error 
Traceback (most recent call last):
  File "D:/ai/DeepQLearning/lunar_lander.py", line 9, in <module>
    env = gym.make('LunarLander-v2')
  File "D:\ai\DeepQLearning\venv\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "D:\ai\DeepQLearning\venv\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "D:\ai\DeepQLearning\venv\lib\site-packages\gym\envs\registration.py", line 72, in make
    cls = load(self._entry_point)
  File "D:\ai\DeepQLearning\venv\lib\site-packages\gym\envs\registration.py", line 18, in load
    fn = getattr(mod, attr_name)
AttributeError: module 'gym.envs.box2d' has no attribute 'LunarLander'

**Comment by salos1982** [comment]
I've already found issue. I need to install box2d

**Comment by philtabor** [comment]
I made the same mistake :) It's not clear from the OpenAI gym docs, so don't feel bad.
