### ISSUE TITLE
Error in Store_transition in pytorch dqns 

### ISSUE THREAD

**Issue by Vis03al** [philtabor/Youtube-Code-Repository#54]
In "main_torch_dqn_lunar_lander_2020.py" file 

--> self.state_memory[index] = state
It says 
"ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1"

When i alter few things to get rid off this error  i am getting into another error 
,could you help me out

**Comment by alvynabranches** [comment]
Traceback (most recent call last):
  File "/home/alvynabranches/aichess/lunar_lander.py", line 32, in <module>
    agent.store_transition(observation, action, reward, observation_, int(done))
  File "/home/../aichess/engines/dddqn.py", line 111, in store_transition
    self.memory.store_transition(state, action, reward, state_, done)
  File "/home/../aichess/engines/dddqn.py", line 22, in store_transition
    self.state_memory[index] = state
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

**Comment by alvynabranches** [comment]
Same error for DQN as well as DDQN

**Comment by philtabor** [comment]
which version of gym are you using?

**Comment by dawmro** [comment]
Find your `env.reset()`
and change it to: `env.reset()[0]`

Why? Look here: 
```
(method) def reset(
    *,
    seed: int | None = None,
    options: dict[str, Any] | None = None
) -> tuple[Any, dict[str, Any]]
```

Another thing: If you are using gymnasium instead of gym, remember that `done` has been replaced with `terminated, truncated`. Addjust your functions accordingly.
